### ISSUE TITLE
Getting error while taping to click

### ISSUE THREAD

**Issue by yogi00195** [Ahmadre/camera#1]
E/CameraCaptureSession(10113): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(10113): android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): checkPidStatus:2264: The camera device has been disconnected
E/CameraCaptureSession(10113): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1009)
E/CameraCaptureSession(10113): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession(10113): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1251)
E/CameraCaptureSession(10113): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession(10113): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:789)
E/CameraCaptureSession(10113): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:245)
E/CameraCaptureSession(10113): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(10113): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(10113): 	at android.os.Looper.loop(Looper.java:223)
E/CameraCaptureSession(10113): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/CameraCaptureSession(10113): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(10113): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/CameraCaptureSession(10113): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/CameraCaptureSession(10113): Caused by: android.os.ServiceSpecificException: checkPidStatus:2264: The camera device has been disconnected (code 4)
E/CameraCaptureSession(10113): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
E/CameraCaptureSession(10113): 	at android.os.Parcel.createException(Parcel.java:2357)
E/CameraCaptureSession(10113): 	at android.os.Parcel.readException(Parcel.java:2340)
E/CameraCaptureSession(10113): 	at android.os.Parcel.readException(Parcel.java:2282)
E/CameraCaptureSession(10113): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:732)
E/CameraCaptureSession(10113): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(10113): 	... 11 more
W/FlutterJNI(10113): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter.io/cameraPlugin/camera0. Response ID: 0
W/FlutterJNI(10113): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter.io/cameraPlugin/camera0. Response ID: 0
I/flutter (10113): CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)

**Comment by yogi00195** [comment]
Solved
